### PR TITLE
add @mikehardy as maintainer of /react-native-share

### PR DESCRIPTION
**Pull request by jgcmarins**

### CODE REVIEW

**Comment by jgcmarins** [comment]
cc @mikehardy

**Comment by mikehardy** [comment]
eek! haha, I suppose I was asking for it...

Incidentally, how does one add an entry to that table? The device closest to my day-job is react-native-device-info and it was just re-parented to react-native-community while I'm picking up the baton on it. To help people find it it might be nice to have an entry there

https://github.com/react-native-community/react-native-device-info/graphs/contributors?from=2018-06-12&to=2019-03-31&type=c

**Comment by kelset** [comment]
> eek! haha, I suppose I was asking for it...

Just to clarify, because I'm a bit confused - are you maintaining rn-share?

> Incidentally, how does one add an entry to that table? The device closest to my day-job is react-native-device-info and it was just re-parented to react-native-community while I'm picking up the baton on it. To help people find it it might be nice to have an entry there


Which table are you referring to? This .md file? A simple PR is enough if that's what you are asking 😅
So you are also a maintainer of device-info?

**Comment by jgcmarins** [comment]
@mikehardy, I thought it would be fair. You've been helping a lot answering issues and reviewing PRs.

**Comment by mikehardy** [comment]
> Just to clarify, because I'm a bit confused - are you maintaining rn-share?

Yes - I am helping maintain rn-share

> Which table are you referring to? This .md file? A simple PR is enough if that's what you are asking 
> So you are also a maintainer of device-info?

Yes I am also a maintainer of device-info, I'll make a PR to add it to the table here

Thanks!

**Comment by jgcmarins** [comment]
Great! Ship it!

**Comment by kelset** [comment]
Ok great, thanks folks! And ofc if you are not yet on the Discord, pls dm me over on twitter and I can give you the invite link :)

**Comment by mikehardy** [comment]
Thanks, I just DM'd you, I don't use discord normally but another channel isn't a bad thing in case normal channels aren't working for whatever reason...

**Pull request merged**
