### PR TITLE
Add react-native-permissions

### PR DESCRIPTION
**Pull request by zoontek**
# Summary

Add react-native-permissions to the organisation.
The next major version will come (very) soon.

### CODE REVIEW

**Comment by MateusAndrade** [comment]
@kelset anyone that is member of react-native-community can merge this PR's without any problem?

**Comment by kelset** [comment]
I think so, because of #40 :D
Probably I should add a codeowners that adds me as required reviwer but this repo is a bit of an edge case so I'm not sure it should be the way to go.

But yeah I'll take care of this today, sorry but last week was ChainReact and I was swamped with things to do.

---

Also, the repo is still under his owner -> https://github.com/yonahforst/react-native-permissions so until that's transferred to me and then to the RNComm we shouldn't merge this yet.

**Comment by yonahforst** [comment]
hey @kelset, I just transferred the repo to you :) thanks for keeping this alive, you guys!! 💝

**Comment by kelset** [comment]
No, thank you all for taking care of this proj! Now the repo is live https://github.com/react-native-community/react-native-permissions 🎉

**Comment by zoontek** [comment]
Now let's ship this new version 😃

**Pull request merged**
